apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  # different name
  name: lessons-certificate
  namespace: lessons
spec:
  # dedicate secret for the TLS cert
  secretName: lessons-certificate-secret
  issuerRef:
    # referencing the production issuer
    name: it-incubator-common-acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - lessons.staging.it-incubator.ru
